//
// Created by Taha Rashid on 2024-11-19.
//

#ifndef UOSM_TELEMETRY_PICO_ACCELEROMETER_H
#define UOSM_TELEMETRY_PICO_ACCELEROMETER_H

void InitAccelerometerTask();

#endif //UOSM_TELEMETRY_PICO_ACCELEROMETER_H
