//
// Created by Jeremy Cote on 2024-07-21.
//

#ifndef UOSM_TELEMETRY_PICO_CURRENTSENSORTASK_H
#define UOSM_TELEMETRY_PICO_CURRENTSENSORTASK_H

void InitCurrentSensorTask();

#endif //UOSM_TELEMETRY_PICO_CURRENTSENSORTASK_H
