//
// Created by Jeremy Cote on 2024-07-21.
//

#ifndef UOSM_TELEMETRY_PICO_INTERNALCOMMSTASK_H
#define UOSM_TELEMETRY_PICO_INTERNALCOMMSTASK_H

void InitInternalCommsTask();

#endif //UOSM_TELEMETRY_PICO_INTERNALCOMMSTASK_H
