//
// Created by Jeremy Cote on 2024-07-21.
//

#ifndef UOSM_TELEMETRY_PICO_RTOS_H
#define UOSM_TELEMETRY_PICO_RTOS_H

#define TASK_LOW_PRIORITY 1
#define TASK_MEDIUM_PRIORITY 2
#define TASK_HIGH_PRIORITY 3

#endif //UOSM_TELEMETRY_PICO_RTOS_H
